### ISSUE TITLE
merge with my code

### ISSUE THREAD

**Issue by rhoconlinux** [benwhalley/atom-language-stata#1]
You can take a look to this https://github.com/rhoconlinux/language-do
If you want... 

I figured out how to do variable like commenting, and imported the commands definitions from the sublime pack. It has autocomplete features, etc. I couldn't upload it to the repos (i don't know why), but the work is done. 

So, you can use my code and merge it with yours, so we all have a nicer package. If you like. 

Cheers. :)

**Comment by yimingli** [comment]
Hi @rhoconlinux , I was just wondering whether there has been any progress in this. Thanks!

**Comment by rhoconlinux** [comment]
Sorry man, I've been closing my PhD thesis and I am really out of time and almost disappeared. :(
I'll let you know when I'm on this as soon as I can :)

**Comment by puterleat** [comment]
I'm closing this for now, but happy to revisit with a PR
