### ISSUE TITLE
Problem loading from source

### ISSUE THREAD

**Issue by nickeubank** [benwhalley/atom-language-stata#10]
Trying to modify, but when I git clone the master branch and symlink into Atom, I get a problem with the `stata.cson` file: 

    /Users/Nick/.atom/packages/language-stata/grammars/stata.cson: unmatched OUTDENT in /Users/Nick/.atom/packages/language-stata/grammars/stata.cson
    Hide Stack Trace
    [stdin]:31:8: error: unmatched OUTDENT
          {
           ^
      at /Users/Nick/.atom/packages/language-stata/grammars/stata.cson:1:1

Is this a clone issue or problem with master branch?

(also, this repo seems super dead. Is it still active? @puterleat @rhoconlinux ?)

**Comment by benwhalley** [comment]
Oops - just tried and don't seem to be able to transfer it because you already have a clone.

**Comment by nickeubank** [comment]
@benwhalley ah, ok -- should I delete clone, or should i just figure out how to push to atom.io and you can delete yours?
