### ISSUE TITLE
Comment start // problematic when ; delimiter used

### ISSUE THREAD

**Issue by breschke** [benwhalley/atom-language-stata#12]
When `//` is used to start comments in stata while the delimiter is `;`, stata returns an error (see http://www.stata.com/statalist/archive/2004-07/msg00268.html). This is avoided when `//` is preceded by a leading space. This is not a problem with the (more familiar) comment character `*` or with comments that begin with `/*` and end with `*/`. It seems the package previously used the latter style--can this be reinstated? Otherwise, users who delimit with `;` will need to manually comment lines.

**Comment by puterleat** [comment]
Thanks for the catch. Have reverted back to /* in 0.3.0
