### ISSUE TITLE
Feature request: End strings on line-end, rather than matching quotes

### ISSUE THREAD

**Issue by karldw** [benwhalley/atom-language-stata#17]
Stata lets you end strings by just moving to the next line, without closing an opening quote, like this:

```stata
disp "This is a valid statement
* Just a comment, should not be colored as part of the string.
disp "Here's another statement, this time with a closing quote"
```
Currently language-stata (and Github's syntax coloring) looks for matching quotes, so the lines above make Atom think the comment is included as part of the string, and they're colored accordingly.
(Obviously I can avoid writing code like this, but it makes reading others' code more difficult.)

Could language-stata be changed to color strings by the same rules Stata does, with line-ends terminating strings?

**Comment by benwhalley** [comment]
I can see how this might be useful if this happens in other people's code, but it seems like it could be terribly confusing... 

I don't have time right now to fix it, but if you wanted to play with it the language grammar file is here: https://github.com/benwhalley/atom-language-stata/blob/master/grammars/stata.cson     My guess is that you could add something like `^\s*\*|^\/\*\s*` as an additional 'endCapture' for the various string definitions, and this would do what you expect. Atom language grammars are based on TextMate language grammars, which have some reasonable documentation here: https://manual.macromates.com/en/language_grammars

**Comment by karldw** [comment]
Thanks, I'll take a look!

**Comment by kylebarron** [comment]
I saw this issue and fixed it in [language-stata](https://github.com/kylebarron/language-stata) in [version 0.5.22](https://github.com/kylebarron/language-stata/commit/4c2dd96881289f4c12a0586eefcd5ead7e61da23).

![image](https://user-images.githubusercontent.com/15164633/30984211-b3dd6350-a45a-11e7-873d-9839393451a3.png)
