### ISSUE TITLE
Getting "Command not configured for Stata!" for Stata-MP in Linux

### ISSUE THREAD

**Issue by nathanlane** [benwhalley/atom-language-stata#7]
Syntax highlighting works, but I can't seem to get the code to send to Stata: "Command not configured for Stata!" 

I get the error with any .do-file I run, sadly. Is this code able to run with other versions of Stata (beyond SE?)?

(Running both Ubuntu Linux and OS X - Atom 1.4.0 with Script 3.4.1)

**Comment by puterleat** [comment]
I think this is an issue with the Script package, not the language definition.
